kong-db:
  restart: always
  image: postgres:9.4
  ports:
    - 7732:5432/tcp
  volumes:
    - /data/kong/pgdata:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
kong:
  restart: always
  image: kong:0.9.9
  links:
    - kong-db:kong-database
  ports:
    - 8000:8000/tcp
    - 8443:8443/tcp
    - 8001:8001/tcp
    - 7946:7946/tcp
    - 7946:7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
  tty: true
dashboard:
  image: pgbi/kong-dashboard
  links:
    - kong:kong
  ports:
    - 7080:8080/tcp
  tty: true
konga: 
  image: pantsel/konga
  links:
    - kong:kong
  ports:
    - 7300:3000/tcp
    - 7338:1338/tcp
  environment:
    - KONGA_BACKEND_URL={Konga's backend url}
  tty: true
 ##Admin login: admin | password: adminadminadmin
 ##Demo user login: demo | password: demodemodemo
  